### ISSUE TITLE
Проблема с генерацией ключа кэша, не учитывается путь (неймспейс)

### ISSUE THREAD

**Issue by pastuhov** [zhelyabuzhsky/django-bi#3]
файл: bi/lib.py
строка: _cache_key = cache_get_key(str(type(args[0])).split('.')[-2], fn.__name__, args[1:])

вместо `str(type(args[0])).split('.')[-2]` лучше сделать `type(args[0])`, иначе с одинаковыми классами в разных директориях (неймспесах) будут проблемы

**Comment by zhelyabuzhsky** [comment]
да, согласен ... я это сделал из-за разного расположения (в фикстурах тестов проблемы были), пофиксю на относительный путь

спасибо

**Comment by zhelyabuzhsky** [comment]
Пофиксил в 1.0.28
